version: '3'
services:
  nginx:
    container_name: my_nginx
    build: requirements/nginx
    volumes:
      - /home/${USER}/data/web/:/var/www/html
      - /home/tkeil/inception/srcs/requirements/nginx/tools:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mariadb
      - wordpress
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - DB_ROOT_USER=${DB_ROOT_USER}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "9000:9000"
    environment:
      - DB_NAME=${DB_NAME}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - DB_ROOT_USER=${DB_ROOT_USER}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
    external: true
  wordpress_data:
    external: true

networks:
  inception:

