version: '3'
services:
  website:
    image: nginx:latest
    container_name: website
    volumes:
      - /home/tkeil/docker/website:/usr/share/nginx/html:ro
      - /home/tkeil/inception/srcs/requirements/nginx/tools:/etc/nginx/ssl:ro
      - /home/tkeil/inception/srcs/requirements/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
      - 443:443
    restart: always
