version: '3'
services:
  website:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: my_nginx
    volumes:
      - /home/tkeil/docker/website:/var/www/:ro
      - /home/tkeil/inception/srcs/requirements/nginx/tools:/etc/nginx/ssl:ro
      - /home/tkeil/inception/srcs/requirements/nginx/conf/:/etc/nginx/http.d/
    ports:
      - "443:443"
    restart: always
